services:
  django-backend:
    image: marcusvcalves/planner-django-backend
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - data-volume:/code
  react-frontend:
    image: marcusvcalves/planner-react-frontend
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - django-backend
volumes:
  data-volume:
