# Generated by Django 4.2.4 on 2023-08-19 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default='00:00')),
                ('monday_task', models.TextField(max_length=300)),
                ('tuesday_task', models.TextField(max_length=300)),
                ('wednesday_task', models.TextField(max_length=300)),
                ('thursday_task', models.TextField(max_length=300)),
                ('friday_task', models.TextField(max_length=300)),
                ('saturday_task', models.TextField(max_length=300)),
                ('sunday_task', models.TextField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
